from django.urls import path
from . import views

app_name = 'maintenance'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('users/', views.user_list, name='users'),
    path('users/add/', views.user_add, name='user_add'),
    path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('users/<int:pk>/', views.user_detail, name='user_detail'),
    path('users/<int:pk>/profile/', views.user_profile, name='user_profile'),
    path('machines/', views.machine_list, name='machines'),
    path('machines/add/', views.machine_add, name='machine_add'),
    path('machines/<int:pk>/', views.machine_detail, name='machine_detail'),
    path('machines/<int:pk>/edit/', views.machine_edit, name='machine_edit'),
    path('machines/<int:pk>/delete/', views.machine_delete, name='machine_delete'),
    path('spare-parts/', views.spare_parts_list, name='spare_parts_list'),
    path('spare-parts/add/', views.add_spare_part, name='add_spare_part'),
    path('spare-parts/export/excel/', views.export_spare_parts_excel, name='export_spare_parts_excel'),
    path('spare-parts/export/pdf/', views.export_spare_parts_pdf, name='export_spare_parts_pdf'),
    path('spare-parts/<int:pk>/edit/', views.edit_spare_part, name='edit_spare_part'),
    path('spare-parts/<int:pk>/delete/', views.delete_spare_part, name='delete_spare_part'),
    path('spare-parts/<int:pk>/transactions/', views.spare_part_transactions, name='spare_part_transactions'),
    path('spare-parts/<int:spare_part_id>/add-transaction/', views.add_transaction, name='add_transaction'),
    path('transactions/<int:pk>/delete/', views.delete_transaction, name='delete_transaction'),
    path('spare-parts/<int:pk>/', views.spare_part_detail, name='spare_part_detail'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('spare-parts/import/', views.import_spare_parts, name='import_spare_parts'),
    path('purchases/', views.purchase_list, name='purchase_list'),
    path('purchases/add/', views.purchase_add, name='purchase_add'),
    path('purchases/<int:pk>/', views.purchase_detail, name='purchase_detail'),
    path('purchases/<int:pk>/edit/', views.purchase_edit, name='purchase_edit'),
    path('purchases/<int:purchase_id>/items/<int:item_id>/delete/', views.purchase_item_delete, name='purchase_item_delete'),
    path('purchases/<int:purchase_id>/items/<int:item_id>/edit/', views.purchase_item_edit, name='purchase_item_edit'),
    path('purchases/<int:pk>/delete/', views.purchase_delete, name='purchase_delete'),
    path('purchases/export/excel/', views.export_purchases_excel, name='export_purchases_excel'),
    path('purchases/export/pdf/', views.export_purchases_pdf, name='export_purchases_pdf'),
    path('exports/<str:file_type>/', views.export_data, name='export_data'),
    path('faults/', views.fault_list, name='fault_list'),
    path('faults/add/', views.fault_add, name='fault_add'),
    path('faults/<int:pk>/', views.fault_detail, name='fault_detail'),
    path('faults/<int:pk>/resolve/', views.fault_resolve, name='fault_resolve'),
    path('faults/<int:pk>/close/', views.fault_close, name='fault_close'),
    path('faults/<int:pk>/delete/', views.fault_delete, name='fault_delete'),
    path('faults/export/excel/', views.export_faults_excel, name='export_faults_excel'),
    path('faults/export/pdf/', views.export_faults_pdf, name='export_faults_pdf'),
    path('transactions/export/excel/', views.export_transactions_excel, name='export_transactions_excel'),
    path('transactions/export/pdf/', views.export_transactions_pdf, name='export_transactions_pdf'),
    path('spare-parts/export/excel/', views.export_spare_parts_excel, name='export_spare_parts_excel'),
    path('spare-parts/export/pdf/', views.export_spare_parts_pdf, name='export_spare_parts_pdf'),
    path('profile/', views.user_profile, name='user_profile'),
]
