# Generated by Django 5.0.1 on 2025-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_purchaseitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
